import type { Metadata } from "next"
import "./globals.css"
import "highlight.js/styles/github-dark.css"
import TanstackProvider from "@/lib/provider/tanstack-provider"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-background font-googleSansRegular text-white">
        <TanstackProvider>
          <main>{children}</main>
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  )
}
